### ISSUE TITLE
Removing a unidirectional relation field doesn't work

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#1532]
1. Deploy this datamodel:

```graphql
type User {
  id: ID! @unique
  name: String!
}

type Post {
  id: ID! @unique
  title: String
}
```

2. Add `users: [User!]!` field:

```diff
type User {
  id: ID! @unique
  name: String!
}

type Post {
  id: ID! @unique
  title: String
+ users: [User!]!
}
```

3. Create data:

```graphql
mutation b {
  createPost(data: {
    title:"Nilan"
    users: {
      create: {
        name: "Nilan"
      }
    }
  }) {
    id
  }
}
```

4. Query data:

```graphql
query a {
  posts {
    id
    users {
      id
    }
  }
}
```

5. Remove `users` field:

```diff
type User {
  id: ID! @unique
  name: String!
}

type Post {
  id: ID! @unique
  title: String
- users: [User!]!
}
```

`graphcool deploy` leads to this output:

```sh
Changes:

  Post (Type)
  - Deleted field `users`

  PostToUser (Relation)
  - Deleted relation between undefined and undefined
```

6.  Query data, and observe that `users` is still a valid field in the schema. However, the data has been wiped:

```graphql
query a {
  posts {
    id
    users {
      id
    }
  }
}
```

7. Create data, and observe that `users` is still an input field on `createPost`. It still creates the connected `User` node:

```graphql
mutation b {
  createPost(data: {
    title:"Nilan"
    users: {
      create: {
        name: "Nilan"
      }
    }
  }) {
    id
    users {
      id
    }
  }
}
```

8. Now, without changing anything, you can `gc deploy` again and again, getting the same output:

```sh
Changes:

  Post (Type)
  - Deleted field `users`

  PostToUser (Relation)
  - Deleted relation between undefined and undefined
```

**Comment by marktani** [comment]
In this inconsistent project, deploy

```diff
type User {
  id: ID! @unique
  name: String!
+ posts: [Post!]!
}

type Post {
  id: ID! @unique
  title: String
}
```

It leads to this output:

```
Deploying service `abc2` to stage `dev` on cluster `local` 43ms

Changes:

  Post (Type)
  - Deleted field `users`

  User (Type)
  + Created field `posts` of type `[Relation!]!`

Applying changes !
 ▸    java.sql.SQLSyntaxErrorException: (conn=11) Unknown table 'abc2@dev.Post_users'
 ▸    at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)
 ▸    at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
 ▸    at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
 ▸    at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
 ▸    at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
 ▸    at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
 ▸    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
 ▸    at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
 ▸    at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
 ▸    at slick.jdbc.Invoker.first(Invoker.scala:31)
 ▸    at slick.jdbc.Invoker.first$(Invoker.scala:30)
 ▸    at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
 ▸    at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
 ▸    at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
 ▸    at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)
 ▸    at scala.collection.Iterator.foreach(Iterator.scala:929)
 ▸    at scala.collection.Iterator.foreach$(Iterator.scala:929)
 ▸    at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
 ▸    at scala.collection.IterableLike.foreach(IterableLike.scala:71)
 ▸    at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
 ▸    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
 ▸    at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)
 ▸    at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)
 ▸    at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
 ▸    at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
 ▸    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 ▸    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 ▸    at java.lang.Thread.run(Thread.java:748)
 ▸    Caused by: java.sql.SQLException: Unknown table 'abc2@dev.Post_users'
 ▸    Query is: DROP TABLE `abc2@dev`.`Post_users`
 ▸    at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
 ▸    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
 ▸    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
 ▸    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 ▸    at java.lang.reflect.Method.invoke(Method.java:498)
 ▸    at org.mariadb.jdbc.internal.failover.AbstractMastersListener.invoke(AbstractMastersListener.java:376)
 ▸    at org.mariadb.jdbc.internal.failover.FailoverProxy.executeInvocation(FailoverProxy.java:220)
 ▸    at org.mariadb.jdbc.internal.failover.FailoverProxy.invoke(FailoverProxy.java:213)
 ▸    at com.sun.proxy.$Proxy5.executeQuery(Unknown Source)
 ▸    at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
 ▸    ... 24 more
 ▸

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ set -x DEBUG "*"
raven@2.3.0 alert: failed to send exception to sentry: Connection timed out on request to sentry.io
```

**Comment by marktani** [comment]
This was fixed [in the release candidate for Graphcool 1.0](https://github.com/graphcool/graphcool/pull/1318#issuecomment-356417351).
