### ISSUE TITLE
Cannot read property 'publicClusters' of undefined

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#1556]
```
> graphql prepare
TypeError: Cannot read property 'publicClusters' of undefined
```

I am not able to reproduce this error yet, any information would be helpful 🙂

**Comment by ForsakenHarmony** [comment]
`Cluster undefined, that is provided in the graphcoo.yml could not be found.`

**Comment by marktani** [comment]
Oh, how does your `graphcool.yml` look like?

**Comment by marktani** [comment]
In a different context, the same error was returned. Here's the strack trace:

```sh
cs-MacBook-Air:graphcool-server-example c$ yarn seed
yarn run v1.3.2
$ graphql query database/seed.graphql --all -p database & graphql query database/moreSeed.graphql --all -p database
TypeError: Cannot read property 'publicClusters' of undefined
   at Environment.<anonymous> (/Users/c/Desktop/project/graphcool_20171220/graphcool-server-example/node_modules/graphql-config-extension-graphcool/node_modules/graphcool-yml/dist/Environment.js:103:39)
   at step (/Users/c/Desktop/project/graphcool_20171220/graphcool-server-example/node_modules/graphql-config-extension-graphcool/node_modules/graphcool-yml/dist/Environment.js:40:23)
   at Object.next (/Users/c/Desktop/project/graphcool_20171220/graphcool-server-example/node_modules/graphql-config-extension-graphcool/node_modules/graphcool-yml/dist/Environment.js:21:53)
   at fulfilled (/Users/c/Desktop/project/graphcool_20171220/graphcool-server-example/node_modules/graphql-config-extension-graphcool/node_modules/graphcool-yml/dist/Environment.js:12:58)
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:188:7)
TypeError: Cannot read property 'publicClusters' of undefined
   at Environment.<anonymous> (/Users/c/Desktop/project/graphcool_20171220/graphcool-server-example/node_modules/graphql-config-extension-graphcool/node_modules/graphcool-yml/dist/Environment.js:103:39)
   at step (/Users/c/Desktop/project/graphcool_20171220/graphcool-server-example/node_modules/graphql-config-extension-graphcool/node_modules/graphcool-yml/dist/Environment.js:40:23)
   at Object.next (/Users/c/Desktop/project/graphcool_20171220/graphcool-server-example/node_modules/graphql-config-extension-graphcool/node_modules/graphcool-yml/dist/Environment.js:21:53)
   at fulfilled (/Users/c/Desktop/project/graphcool_20171220/graphcool-server-example/node_modules/graphql-config-extension-graphcool/node_modules/graphcool-yml/dist/Environment.js:12:58)
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ForsakenHarmony** [comment]
same stacktrace here

```
service: restaurant-rating_

datamodel: database/datamodel.graphql

cluster: public-watercockatoo-mouse-6455/graphcool-eu1

stage: dev

secret: mysecret123
```

**Comment by maelsan** [comment]
I'm encountering the same problem, whatever command I do with `graphcool`, this error appear.

My `graphcool.yml`:

```
# the name for the service (will be part of the service's HTTP endpoint)
service: nestor-graph

# the cluster and stage the service is deployed to
stage: ${env:GRAPHCOOL_STAGE}
cluster: ${env:GRAPHCOOL_CLUSTER}

# to disable authentication:
# disableAuth: true
secret: ${env:GRAPHCOOL_SECRET}

# the file path pointing to your data model
datamodel: 
  - database/enums.graphql
  - database/address.graphql
  - database/administrator.graphql 
  - database/company.graphql
  - database/configuration.graphql 
  - database/coupon.graphql
  - database/credit.graphql 
  - database/day.graphql
  - database/deal.graphql 
  - database/domains.graphql
  - database/enums.graphql 
  - database/file.graphql
  - database/log.graphql 
  - database/menu.graphql
  - database/menuQuantity.graphql 
  - database/menuStock.graphql
  - database/order.graphql 
  - database/payment.graphql
  - database/place.graphql 
  - database/product.graphql
  - database/productQuantity.graphql 
  - database/productStock.graphql
  - database/restaurant.graphql 
  - database/review.graphql
  - database/slot.graphql
  - database/user.graphql
  - database/zip.graphql
```

Version: `graphcool/1.0.0-beta3.3.1 (darwin-x64) node-v9.2.0`

And the complete error I have:
```
TypeError: Cannot read property 'publicClusters' of undefined
    at Environment.<anonymous> (/Users/mael/.nvm/versions/node/v9.2.0/lib/node_modules/graphcool/node_modules/graphcool-yml/src/Environment.ts:55:19)
    at step (/Users/mael/.nvm/versions/node/v9.2.0/lib/node_modules/graphcool/node_modules/graphcool-yml/dist/Environment.js:40:23)
    at Object.next (/Users/mael/.nvm/versions/node/v9.2.0/lib/node_modules/graphcool/node_modules/graphcool-yml/dist/Environment.js:21:53)
    at fulfilled (/Users/mael/.nvm/versions/node/v9.2.0/lib/node_modules/graphcool/node_modules/graphcool-yml/dist/Environment.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by marktani** [comment]
This is fixed in the latest `graphql-cli`:

```
npm install -g graphql-cli
```
