### ISSUE TITLE
 'graphcool deploy' returns 'The header content contains invalid characters' error

### ISSUE THREAD

**Issue by raeesaa** [graphcool/graphcool#1587]
**Current behavior**

I get following error on running `graphcool deploy` command.

```
Creating stage dev for service test-app... !
 ▸    The header content contains invalid characters
```

Debug logs:

```
deploy run +0ms
  client choosing clusterEndpoint http://localhost:60000/cluster +0ms
  client Sending query +0ms
  client 
  client       query($name: String! $stage: String!) {
  client         project(name: $name stage: $stage) {
  client           name
  client           stage
  client         }
  client       }
  client      +0ms
  client { name: 'test-app', stage: 'dev' } +1ms
Creating stage dev for service design-board...  client choosing clusterEndpoint http://localhost:60000/cluster +3ms
  client Sending query +0ms
  client       mutation addProject($name: String! $stage: String! $secrets: [String!]) {
  client         addProject(input: {
  client           name: $name,
  client           stage: $stage
  client           secrets: $secrets
  client         }) {
  client           project {
  client             name
  client           }
  client         }
  client       }
  client        +0ms
  client { name: 'test-app',
  client   stage: 'dev',
  client   secrets: [ 'mysecret123' ] } +0ms
 !
TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:492:11)
    at ClientRequest.setHeader (_http_outgoing.js:496:3)
    at new ClientRequest (_http_client.js:171:14)
    at request (http.js:39:10)
    at /usr/local/lib/node_modules/graphcool/node_modules/node-fetch/index.js:119:13
    at Promise (<anonymous>)
    at new Fetch (/usr/local/lib/node_modules/graphcool/node_modules/node-fetch/index.js:49:9)
    at Object.Fetch (/usr/local/lib/node_modules/graphcool/node_modules/node-fetch/index.js:37:10)
    at Object.fetch (/usr/local/lib/node_modules/graphcool/node_modules/cross-fetch/dist/node.js:9:20)
    at GraphQLClient.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphql-request/src/index.ts:33:28)
    at step (/usr/local/lib/node_modules/graphcool/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphql-request/dist/src/index.js:21:53)
    at /usr/local/lib/node_modules/graphcool/node_modules/graphql-request/dist/src/index.js:15:71
    at Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/graphcool/node_modules/graphql-request/dist/src/index.js:11:12)
    at GraphQLClient.request (/usr/local/lib/node_modules/graphcool/node_modules/graphql-request/dist/src/index.js:76:16)
    at Client.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Client/Client.ts:146:36)
    at step (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:32:23)
    at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:13:53)
    at /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:3:12)
    at Object.request (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Client/Client.ts:141:39)
    at Client.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Client/Client.ts:326:59)
    at step (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:32:23)
    at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:13:53)
    at /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:3:12)
    at Client.addProject (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:247:16)
    at Deploy.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/src/commands/deploy/index.ts:222:46)
    at step (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:42:23)
    at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:23:53)
    at /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:17:71
    at Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:13:12)
    at Deploy.addProject (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:237:16)
    at Deploy.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/src/commands/deploy/index.ts:133:18)
    at step (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:42:23)
    at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:23:53)
    at fulfilled (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:14:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Versions  of graphcool and graphql-cli**

- graphcool: graphcool/1.0.0-beta3.3.1
- graphql-cli: 2.10.0

**Expected behavior?**

`graphcool deploy` should succeed without error.

**Comment by marktani** [comment]
Does that also happen in the latest beta? `beta4.1.1`

**Comment by raeesaa** [comment]
Upgrading to `beta4.1.1` fixed the issue. Thanks @marktani.
