### ISSUE TITLE
can't install in Windows

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#617]
<a href="https://github.com/tomByrer"><img src="https://avatars2.githubusercontent.com/u/1308419?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomByrer](https://github.com/tomByrer)**
_Thursday Jul 27, 2017 at 09:30 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/131_

----

Win10, using nvm 1.1.3, node 8.2.1 64bit, npm 5.3.0

```cli
λ npm install -g graphcool
module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\tom-byrer\AppData\Roaming\nvm\v8.2.1\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
module.js:487
    throw err;
    ^
```

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jul 27, 2017 at 10:28 GMT_

----

That seems to be a common error message when something in your npm install is corrupted. Maybe try this suggested approach: https://stackoverflow.com/a/41000891/1176596?

**Comment by timsuchanek** [comment]
Seems to be an old issue, closing this now. Feel free to reopen if it's still a problem.
