### ISSUE TITLE
Strange query against etc/passwd and win.ini while running example app?

### ISSUE THREAD

**Issue by thebetterjort** [graphcool/graphcool#775]
I'm currently running some example code with graph cool + next.js. I dockertize the image and was developing when out of the blue I see these errors. Somebody was trying to get a hold of /etc/passwd and win.ini files.

Should I be concerned with security of graph.cool?

```
BadRequestError: failed to decode param "%80../%80../%80../%80../%80../%80../windows/win.ini"
    at decodeParam (/usr/src/app/node_modules/path-match/index.js:36:11)
    at Object.match (/usr/src/app/node_modules/path-match/index.js:23:28)
    at _loop (/usr/src/app/node_modules/next/dist/server/router.js:72:24)
    at Router.match (/usr/src/app/node_modules/next/dist/server/router.js:109:22)
    at Server._callee16$ (/usr/src/app/node_modules/next/dist/server/index.js:792:34)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
BadRequestError: failed to decode param "%80../%80../%80../%80../%80../%80../winnt/win.ini"
    at decodeParam (/usr/src/app/node_modules/path-match/index.js:36:11)
    at Object.match (/usr/src/app/node_modules/path-match/index.js:23:28)
    at _loop (/usr/src/app/node_modules/next/dist/server/router.js:72:24)
    at Router.match (/usr/src/app/node_modules/next/dist/server/router.js:109:22)
    at Server._callee16$ (/usr/src/app/node_modules/next/dist/server/index.js:792:34)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
BadRequestError: failed to decode param "%c0.%c0./%c0.%c0./%c0.%c0./%c0.%c0./%c0.%c0./windows/win.ini"
    at decodeParam (/usr/src/app/node_modules/path-match/index.js:36:11)
    at Object.match (/usr/src/app/node_modules/path-match/index.js:23:28)
    at _loop (/usr/src/app/node_modules/next/dist/server/router.js:72:24)
    at Router.match (/usr/src/app/node_modules/next/dist/server/router.js:109:22)
    at Server._callee16$ (/usr/src/app/node_modules/next/dist/server/index.js:792:34)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
BadRequestError: failed to decode param "%c0.%c0./%c0.%c0./%c0.%c0./%c0.%c0./%c0.%c0./winnt/win.ini"
    at decodeParam (/usr/src/app/node_modules/path-match/index.js:36:11)
    at Object.match (/usr/src/app/node_modules/path-match/index.js:23:28)
    at _loop (/usr/src/app/node_modules/next/dist/server/router.js:72:24)
    at Router.match (/usr/src/app/node_modules/next/dist/server/router.js:109:22)
    at Server._callee16$ (/usr/src/app/node_modules/next/dist/server/index.js:792:34)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
BadRequestError: failed to decode param "%c0%2e%c0%2e/%c0%2e%c0%2e/%c0%2e%c0%2e/%c0%2e%c0%2e/windows/win.ini"
    at decodeParam (/usr/src/app/node_modules/path-match/index.js:36:11)
    at Object.match (/usr/src/app/node_modules/path-match/index.js:23:28)
    at _loop (/usr/src/app/node_modules/next/dist/server/router.js:72:24)
    at Router.match (/usr/src/app/node_modules/next/dist/server/router.js:109:22)
    at Server._callee16$ (/usr/src/app/node_modules/next/dist/server/index.js:792:34)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
BadRequestError: failed to decode param "%c0%2e%c0%2e/%c0%2e%c0%2e/%c0%2e%c0%2e/%c0%2e%c0%2e/winnt/win.ini"
    at decodeParam (/usr/src/app/node_modules/path-match/index.js:36:11)
    at Object.match (/usr/src/app/node_modules/path-match/index.js:23:28)
    at _loop (/usr/src/app/node_modules/next/dist/server/router.js:72:24)
    at Router.match (/usr/src/app/node_modules/next/dist/server/router.js:109:22)
    at Server._callee16$ (/usr/src/app/node_modules/next/dist/server/index.js:792:34)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
BadRequestError: failed to decode param "%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/windows/win.ini"
    at decodeParam (/usr/src/app/node_modules/path-match/index.js:36:11)
    at Object.match (/usr/src/app/node_modules/path-match/index.js:23:28)
    at _loop (/usr/src/app/node_modules/next/dist/server/router.js:72:24)
    at Router.match (/usr/src/app/node_modules/next/dist/server/router.js:109:22)
    at Server._callee16$ (/usr/src/app/node_modules/next/dist/server/index.js:792:34)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
BadRequestError: failed to decode param "%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/winnt/win.ini"
    at decodeParam (/usr/src/app/node_modules/path-match/index.js:36:11)
    at Object.match (/usr/src/app/node_modules/path-match/index.js:23:28)
    at _loop (/usr/src/app/node_modules/next/dist/server/router.js:72:24)
    at Router.match (/usr/src/app/node_modules/next/dist/server/router.js:109:22)
    at Server._callee16$ (/usr/src/app/node_modules/next/dist/server/index.js:792:34)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
{ Error: ENOTDIR: not a directory, stat '/etc/passwd/index.js'
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'stat',
  path: '/etc/passwd/index.js' }
{ Error: ENOTDIR: not a directory, stat '/etc/passwd/index.js'
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'stat',
  path: '/etc/passwd/index.js' }
{ Error: ENOTDIR: not a directory, stat '/etc/passwd/index.js'
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'stat',
  path: '/etc/passwd/index.js' }
BadRequestError: failed to decode param "%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/etc/passwd"
    at decodeParam (/usr/src/app/node_modules/path-match/index.js:36:11)
    at Object.match (/usr/src/app/node_modules/path-match/index.js:23:28)
    at _loop (/usr/src/app/node_modules/next/dist/server/router.js:72:24)
    at Router.match (/usr/src/app/node_modules/next/dist/server/router.js:109:22)
    at Server._callee16$ (/usr/src/app/node_modules/next/dist/server/index.js:792:34)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13

```

**Comment by dpetrick** [comment]
Hi @thebetterjort,

thank you for the report. A couple of questions:
- Can you please provide more context for the issue? The environment you're developing on, the `package.json`, node version, etc.
- What does your dockerfile look like? Is the docker container bound to the loopback adapter or exposed to the external network?
- Do you have more containers running?
- Is the issue reliably reproducable, or did it happen once and not again?
- Can you lock down the network (e.g. by shutting down the external network interface) and see if the attack persists? Can you grab the IPs if the issue continues?

Thanks.

**Comment by thebetterjort** [comment]
I apologize for sounding the alarm without consulting out network admins first. 
It was our nessus-vulnerability-scanner running.
