### ISSUE TITLE
Renaming a function file results in unexpected errors

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#896]
**Current behavior**

Renaming a function file & updating the file reference in `graphcool.yml` and then deploying will break the function at runtime.

**Reproduction**

```sh
graphcool init
graphcool deploy
```

rename hello.js to hello2.js on the file system, and update graphcool.yml accordingly:

```yml
functions:
  hello:
    handler:
      code: src/hello2.js
    type: resolver
    schema: src/hello.graphql
```

note that the function key is still `hello`.

deploy:

```sh
graphcool deploy
```

query

```graphql
query {
  hello {
    message
  }
}
```

the result will be `null`. Error from logs:

```json
"logs": [
    {
      "Unable to import module ": "tion.Module._resolveFilename (module.js:469:15)\n    at Function.Module._load (module.js:417:25)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)"
    }
  ],
  "returnValue": {
    "errorMessage": "Cannot find module '/var/task/src/hello2-lambda'",
    "errorType": "Error",
    "stackTrace": [
      "Function.Module._load (module.js:417:25)",
      "Module.require (module.js:497:17)",
      "require (internal/module.js:20:19)"
    ]
  }
```

**Expected behavior?**

The query works & the function is correctly deployed.

**Comment by marktani** [comment]
This is now fixed 🎉
