### ISSUE TITLE
Unexpected token = when using graphcool-lib in legacy projects

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#898]
```graphql
type AdditionPayload {
  sum: Int!
}

extend type Query {
  add(a: Int! b: Int!): AdditionPayload
}
```

```js
const fromEvent = require("graphcool-lib").fromEvent

module.exports = function sum(event) {
  return { data: { sum: 12 } }
}
```

running this function results in this error:

```js
SyntaxError: Unexpected token =
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Module._compile (/data/sandbox/lib/module.js:127:21)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at WebtaskModule.require (/data/sandbox/lib/module.js:101:19)
at require (/data/sandbox/lib/module.js:136:21)
at Object.<anonymous> (/data/io/1d981a037e1743f79bc44df450174e98/webtask.js:1:81)
at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:95:34)
```

**Comment by timsuchanek** [comment]
Fixed by https://github.com/graphcool/graphcool-lib/releases/tag/v0.1.1
