### ISSUE TITLE
Cannot read property 'serviceId' of undefined when using graphcool-lib in legacy projects

### ISSUE THREAD

**Issue by ludovicgueth** [graphcool/graphcool#901]
Hi,

I'm using resolvers functions in the console. I get error from graphcool-lib since I saved again my functions

### types :
```graphql
type SignupEmailUserPayload {
  id: ID!
}

extend type Mutation {
  signupEmailUser(email: String!, password: String!): SignupEmailUserPayload
}
```

### functions :
```js
const fromEvent = require("graphcool-lib").fromEvent

module.exports = function(event) {
  const graphcool = fromEvent(event)
  return { id: "ID" }
}
```

### Error :
CODE: 500
MESSAGE: Cannot read property 'serviceId' of undefined
ERROR: Script generated an unhandled synchronous exception.

```js
TypeError: Cannot read property 'serviceId' of undefined
at Object.fromEvent (/data/_verquire/graphcool-lib/0.1.3/node_modules/graphcool-lib/dist/src/index.js:163:49)
at module.exports (/data/io/23d6f9cf1e594725a8ac5fff930cd115/webtask.js:6:34)
at /data/io/23d6f9cf1e594725a8ac5fff930cd115/webtask.js:40:24
at Async.series.Request.get.Async.series.Async.forEachOf.createError.code (/data/sandbox/lib/sandbox.js:854:33)
at /data/sandbox/node_modules/async/dist/async.js:3853:24
at replenish (/data/sandbox/node_modules/async/dist/async.js:946:17)
at iterateeCallback (/data/sandbox/node_modules/async/dist/async.js:931:17)
at /data/sandbox/node_modules/async/dist/async.js:906:16
at /data/sandbox/node_modules/async/dist/async.js:3858:13
at /data/sandbox/lib/sandbox.js:928:24
```

**Comment by ludovicgueth** [comment]
Seems to be resolved by the graphcool-lib update [https://github.com/graphcool/graphcool-lib/releases/tag/v0.1.3](https://github.com/graphcool/graphcool-lib/releases/tag/v0.1.3)

I close the issue

**Comment by Anujraval24** [comment]
what's the fix?
